FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY [".", "."]
RUN dotnet restore "./API.sln"
COPY . .
RUN dotnet build "./API.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./API.IntegrationTest.Console/API.IntegrationTest.Console.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.IntegrationTest.Console.dll"]